Update scilpy & tractometry
scilus/rbx_flow pull request #2
Opened 2020-07-02 22:39 UTC by frheault

Adaptation to the recent modification in scilpy

2020-09-17 17:28 UTC, alexjoa commented on main.nf
> +        .fromFilePairs("$root/**/{*tracking.trk,*fa.nii.gz}",
The name anat should be changed to fa in USAGE too.

2020-10-02 12:26 UTC, GuillaumeTh reviewed
Don't tested yet. A small comment about naming convention. Don't tested yet. @frheault Could you give me the path of the singularity used for this PR or at least scilpy commit number ?

2020-10-02 12:26 UTC, GuillaumeTh commented on main.nf
> +    .into{anat_for_registration;anat_for_reference_c;anat_for_reference_b}
I don't like variable naming. I prefer something like `anat_for_transform_centroids`

2020-10-02 13:11 UTC, GuillaumeTh requested changes
The pipeline crash. Maybe a too old version of the models ?

```
File "/usr/local/lib/python3.7/dist-packages/scilpy-0.2.dev0-py3.7-linux-x86_64.egg/scilpy/segment/voting_scheme.py", line 73, in _init_bundles_tag
      for key in self.config.keys():
  AttributeError: 'list' object has no attribute 'keys'
```

2020-10-02 13:11 UTC, GuillaumeTh commented on main.nf
> +atlas_anat = Channel.fromPath("$params.atlas_anat")
Could be nice to test if all the mandatory arguments are differents than false. Something like in TractoFlow just to be more robust.

2020-10-02 16:21 UTC, GuillaumeTh requested changes
Worked well with the atlas you gave me. Please fix the comments and I will approve after.

2020-10-02 18:50 UTC, frheault commented
@GuillaumeTh Done

2020-10-17 12:11 UTC, mdesco approved these changes
Aside from my comestic suggestions. This works and was tested with and without the singularity tractoflow-scilpy-rc2

2020-10-17 12:11 UTC, mdesco commented on USAGE
> +                                    │   ├── *fa.nii.gz
Does it really need to be an FA? 
For instance, in my test case, I have b0 and I believe it should work, no?

Can you add something in the help about that please?

2020-10-17 12:11 UTC, mdesco commented on USAGE
> +                                    │   ├── *fa.nii.gz
Also,

1. Can you provide a link to your zenodo URL please
2. Can you add a centroids directory or download on the zenodo?

2020-10-17 12:11 UTC, mdesco commented on USAGE
> +                                    │   ├── *fa.nii.gz
Finally, a lot of our flows use --root, others use --input. Can we harmonize this?

--input or --root?

2020-10-17 12:11 UTC, mdesco commented on USAGE
> +                                    │   ├── *fa.nii.gz
--input

2020-10-18 15:04 UTC, frheault commented on USAGE
> +                                    │   ├── *fa.nii.gz
It should work with anything, but I want to leave *fa.nii.gz as an input name

2020-10-21 15:59 UTC, GuillaumeTh approved these changes
Tested and worked well. Good job ! :beers:

2020-10-21 16:00 UTC, merged